gourmand/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.index, name='category'),
    path('detail/<int:recipe_id>', views.detail, name='detail'),
    path('edit', views.edit, name='new'),
    path('edit/<int:recipe_id>', views.edit, name='edit'),
]

recipes/models.py
from django.db import models
from django.core.validators import RegexValidator
from tinymce import models as tinymce_models


class Category(models.Model):
    name = models.CharField(max_length=20)
    order = models.IntegerField(default=100)

    def __str__(self):
        return self.name
    

class Recipe(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    quantity = models.CharField(max_length=50)
    instructions = tinymce_models.HTMLField()
    image = models.ImageField(default="img/default.png", upload_to="img/")
    likes = models.IntegerField(default=0)
    vegan = models.BooleanField(default=False)
    published = models.DateTimeField(auto_now_add=True)
    password = models.CharField(
        max_length=200, 
        null=True, 
        blank=True, 
        validators=[RegexValidator(
            regex='^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$',
            message='Le mot de passe doit contenir au moins 8 caractères, dont au moins un chiffre, une minuscule et une majuscule'
        )]
    )
    
    def __str__(self):
        return f"{self.category.name} / {self.title}"
    

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    optional = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.recipe.pk} - {self.name}"
    

recipes/forms.py
from django import forms
from .models import Recipe, Category, Ingredient
from tinymce.widgets import TinyMCE


class SearchForm(forms.Form):
    query = forms.CharField(label='Nom ou ingrédient', required=False)
    vegan = forms.BooleanField(label='Végane', required=False)
    sort = forms.IntegerField(widget=forms.HiddenInput(), initial=0)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'vegan', 'category', 'quantity', 'image', 'description', 'password', 'confirmation', 'instructions' ]
        labels = {
            'title': 'Nom',
            'vegan': 'Végane',
            'category': 'Catégorie',
            'quantity': 'Quantité',
            'image': 'Image',
            'description': 'Description',
            'password': 'Mot de passe',
            'instructions': 'Instructions',
        },
        widgets = {
            'image': forms.FileInput(),
            'instructions': TinyMCE(attrs={'cols': 80, 'rows': 30}),
            'password': forms.PasswordInput(),
        }
    confirmation = forms.CharField(
        label='Confirmer le mot de passe', 
        widget=forms.PasswordInput(),
        required=False
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.order_by('order'),
        widget=forms.Select()
    )

    def clean_confirmation(self):
        password     = self.cleaned_data.get('password')
        confirmation = self.cleaned_data.get('confirmation')
        if password != confirmation:
            raise forms.ValidationError('Les mots de passe ne correspondent pas')
        return confirmation


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'optional']
        labels = {
            'name': 'Nom',
            'optional': 'Facultatif',
        }

recipes/views.py
from django.http import HttpResponse
from django.template import loader
from django.db.models import Q
from django.forms import modelformset_factory
from .models import Category, Recipe, Ingredient
from .forms import SearchForm, RecipeForm, IngredientForm


SORTS = [('Likes', '-likes'), ('Récents', '-published'), ('Alphabétique', 'title')]


def filter(recipes, keyword, vegan_only):
    filter = Q(title__icontains=keyword) | Q(ingredient__name__icontains=keyword)
    if vegan_only:
        filter &= Q(vegan=True)
    return recipes.filter(filter).distinct()


def get_context(request, context):
    like = request.GET.get('like', None)
    if like:
        recipe = Recipe.objects.get(pk=like)
        recipe.likes += 1
        recipe.save()
    return {
        'categories': Category.objects.all().order_by('order'),
        'category_id': None,
    }|context


def index(request, category_id=None):
    sort_id = int(request.GET.get('sort', 0))
    recipes = Recipe.objects.filter(category=category_id) if category_id else Recipe.objects.all()
    search = SearchForm(request.GET.dict()|{'sort': sort_id})
    if(search.is_valid()):
        recipes = filter(
            recipes, 
            search.cleaned_data['query'], 
            search.cleaned_data['vegan']
        )
    context = get_context(request, {
        'sorts'      : [sort[0] for sort in SORTS],
        'sort_id'    : sort_id,
        'recipes'    : recipes.order_by(SORTS[sort_id][1]),
        'category_id': category_id,
        'search'     : search,
    })
    template = loader.get_template('index.html')
    return HttpResponse(template.render(context, request))


def detail(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)
    context = get_context(request, {
        'recipe': recipe,
        'category_id': recipe.category.pk
    })
    template = loader.get_template('detail.html')
    return HttpResponse(template.render(context, request))


def edit(request, recipe_id=None):
    recipe = Recipe.objects.get(pk=recipe_id) if recipe_id else None
    form = RecipeForm(
        request.POST or None, 
        request.FILES or None, 
        instance=recipe
    )
    IngredientFormSet = modelformset_factory(
        Ingredient, 
        form=IngredientForm,
        can_delete=True,
        extra= 3 if recipe_id else 10
    )
    ingredients = IngredientFormSet(
        request.POST or None, 
        queryset=Ingredient.objects.filter(recipe=recipe)
    )
    if request.method == 'POST':
        ok = form.is_valid() and ingredients.is_valid()
        ko = not ok
    else:
        ok = ko = False
    if ok:
        form.save()
        for ingredient in ingredients:
            if ingredient.is_valid() and ingredient.has_changed():
                ingredient.instance.recipe = form.instance
                ingredient.save()
        reload = False
        for ingredient in ingredients.deleted_forms:
            if ingredient.instance.id:
                ingredient.instance.delete()
            reload = True
        if reload:
            ingredients = IngredientFormSet(queryset=Ingredient.objects.filter(recipe=recipe))
    context = get_context(request, { 
        'ok': ok, 
        'ko': ko,
        'form': form, 
        'recipe': recipe,
        'ingredients': ingredients,
    })
    template = loader.get_template('edit.html')
    return HttpResponse(template.render(context, request))

recipes/templates/appbase.html
{% extends 'base.html' %}

{% block menu %}
{% for category in categories %}
<li class="nav-item">
  <a class="nav-link{% if category_id == category.pk %} active{% endif %}" aria-current="page"
    href="{% url 'category' category.pk %}">{{ category.name }}</a>
</li>
{% endfor %}
{% endblock %}

recipes/templates/detail.html
{% extends "appbase.html" %}
{% load static %}

{% block title %} - {{ recipe.title }}{% endblock %}

{% block content %}

<div class="row">
  <div class="col-12 detail-header" style="background-image: url('{{ recipe.image.url }}');">
    <div class="float-end">
      <a href="{% url 'edit' recipe.pk %}" class="btn btn-secondary btn-sm">Contribuer</a>
    </div>
    <div class='col-10 col-lg-7 offset-1 p-5 py-4 my-5 detail-header-text'>
      <h1>{{ recipe.title }}</h1>
      <p class="lead">{{ recipe.description }}</p>
    </div>
  </div>
  <div class="col-12 col-md-4 mt-2">
    <h2>Ingredients</h2>
    <ul>
      {% for ingredient in recipe.ingredient_set.all %}
      <li>{{ ingredient.name }}{% if ingredient.optional %} (facultatif){% endif %}</li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-12 col-md-8 mt-2">
    <a href="?like={{ recipe.pk }}" class="btn btn-secondary float-end">J'aime
      <span class="badge text-bg-primary">{{ recipe.likes }}</span>
    </a>
    {% autoescape off %}{{ recipe.instructions }}{% endautoescape %}
  </div>
</div>
{% endblock %}

recipes/templates/edit.html
{% extends "appbase.html" %}
{% load static %}

{% block title %} - 
  {% if recipe == None %}
  Proposer une recette
  {% else %}
  {{ recipe.title }}
  {% endif %}
{% endblock %}

{% block content %}

{% load widget_tweaks %}

{% if ok %}
  <div class="alert alert-success">Recette enregistrée !</div>
{% elif ko %}
  <div class="alert alert-danger">
    <p>Erreur(s) de validation : </p>
    <ul>
    {% for field, errlist in form.errors.items %}
      {% for err in errlist %}
        <li>{{ err }}</li>
      {% endfor %}
    {% endfor %}
    </ul>
  </div>
{% endif %}
<form class="col-12 py-3" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-4">
      <table class="ingredients table table-hover">
        <tr>
          <th>Ingredient</th>
          <th>Option</th>
          <th>Suppr.</th>
        </tr>
      {{ ingredients.management_form }}
      {% for form in ingredients %}
      <tr {% if form.errors %}
          class="table-danger"
        {% elif form.is_valid and form.has_changed %}
          class="table-success"
        {% endif %}>
        <td>
          {{ form.hidden_fields|join:'' }}
          {% render_field form.name class="form-control" %}
        </td>
        <td>{{ form.optional }}</td>
        <td>{{ form.DELETE }}</td>
      </tr>
      {% endfor %}
      </table>
    </div>
    <div class="col-8">
      {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
          {% if field|widget_type in 'radioselect checkboxinput' %}
          {{ field }}
          {% else %}
          {% render_field field|add_error_class:'is-invalid' class="form-control" %}
          <div class="invalid-feedback">
            {% for err in field.errors %}
            {{ err }}
            {% endfor %}
          </div>
          {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
  <input type="submit" class="btn btn-primary" value="Enregistrer">
</form>

{% endblock %}

recipes/templates/index.html
{% extends "appbase.html" %}
{% load static %}

{% block title %} - Recettes{% endblock %}

{% block content %}
<section class="row py-3 text-center container">
  <form class="col-8 form-inline">
    {{ search }}
    <input type="submit" value="Filtrer">
  </form>
  <form class="col-4">
    <select name="sort" onchange="this.form.submit()">
      {% for sort in sorts %}
      <option {% if sort_id == forloop.counter0 %}selected{% endif %} value="{{ forloop.counter0 }}">
        {{ sort }}
      </option>
      {% endfor %}
    </select>
  </form>
</section>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
  {% for recipe in recipes %}
  <div class="col">
    <div class="card shadow-sm">
      <img src="{{ recipe.image.url }}" class="card-img-top" width="100%" alt="Photo de {{ recipe.title|escape }}"
        focusable="false">
      <div class="card-body">
        <h3 class="card-title">{{ recipe.title }}</h3>
        <p class="card-text">{{ recipe.description }}</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <a href="{% url 'detail' recipe.id %}" class="btn btn-sm btn-outline-secondary">Voir</a>
            <a href="?like={{ recipe.pk }}" class="btn btn-sm btn-outline-secondary">+1 j'aime</a>
          </div>
          <small class="text-body-secondary">{{ recipe.likes }} j'aime</small>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Site du gourmand">
  <meta name="author" content="S.Labasse">
  <title>Gourmand{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  {{ form.media }}
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a name="top" class="navbar-brand" href="/"><strong>Gourmand</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link{% if category_id == None %} active{% endif %}" aria-current="page"
                href="{% url 'index' %}">Recettes</a>
            </li>
            {% block menu %}{% endblock %}
          </ul>
          <ul class="navbar-nav d-flex">
            <li class="nav-item">
              <a class="btn btn-primary" href="{% url 'new' %}">Proposer une recette</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main class="container">
    {% block content %}{% endblock %}
  </main>

  <footer class="text-body-secondary py-5">
    <div class="container">
      <p class="float-end mb-1"><a href="#top">Haut de page</a></p>
      <p class="mb-1">Petites recettes rapides et simples.</p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

templates/django/forms/attrs.html
{% for name, value in attrs.items %}{% if value is not False %} {{ name }}{% if value is not True %}="{{ value|stringformat:'s' }}"{% endif %}{% endif %}{% endfor %}

templates/django/forms/div.html
{{ errors }}
{% if errors and not fields %}
  <div>{% for field in hidden_fields %}{{ field }}{% endfor %}</div>
{% endif %}
{% for field, errors in fields %}
  <div{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {{ field.as_field_group }}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
</div>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/field.html
{% if field.use_fieldset %}
  <fieldset{% if field.help_text and field.auto_id and "aria-describedby" not in field.field.widget.attrs %} aria-describedby="{{ field.auto_id }}_helptext"{% endif %}>
  {% if field.label %}{{ field.legend_tag }}{% endif %}
{% else %}
  {% if field.label %}{{ field.label_tag }}{% endif %}
{% endif %}
{% if field.help_text %}<div class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</div>{% endif %}
{{ field.errors }}
{{ field }}{% if field.use_fieldset %}</fieldset>{% endif %}

templates/django/forms/formsets/div.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_div }}{% endfor %}

templates/django/forms/formsets/p.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_p }}{% endfor %}

templates/django/forms/formsets/table.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_table }}{% endfor %}

templates/django/forms/formsets/ul.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_ul }}{% endfor %}

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}>{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/p.html
{{ errors }}
{% if errors and not fields %}
  <p>{% for field in hidden_fields %}{{ field }}{% endfor %}</p>
{% endif %}
{% for field, errors in fields %}
  {{ errors }}
  <p{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {% if field.label %}{{ field.label_tag }}{% endif %}
    {{ field }}
    {% if field.help_text %}
      <span class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</span>
    {% endif %}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
  </p>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/table.html
{% if errors %}
  <tr>
    <td colspan="2">
      {{ errors }}
      {% if not fields %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endif %}
{% for field, errors in fields %}
  <tr{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    <th>{% if field.label %}{{ field.label_tag }}{% endif %}</th>
    <td>
      {{ errors }}
      {{ field }}
      {% if field.help_text %}
        <br>
        <span class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</span>
      {% endif %}
      {% if forloop.last %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/ul.html
{% if errors %}
  <li>
    {{ errors }}
  {% if not fields %}
    {% for field in hidden_fields %}{{ field }}{% endfor %}
  {% endif %}
  </li>
{% endif %}
{% for field, errors in fields %}
  <li{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {{ errors }}
    {% if field.label %}{{ field.label_tag }}{% endif %}
    {{ field }}
    {% if field.help_text %}
      <span class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</span>
    {% endif %}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
  </li>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/widgets/checkbox.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/checkbox_select.html
{% include "django/forms/widgets/multiple_input.html" %}

templates/django/forms/widgets/clearable_file_input.html
{% if widget.is_initial %}{{ widget.initial_text }}: <a href="{{ widget.value.url }}">{{ widget.value }}</a>{% if not widget.required %}
<input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"{% if widget.attrs.disabled %} disabled{% endif %}{% if widget.attrs.checked %} checked{% endif %}>
<label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>{% endif %}<br>
{{ widget.input_text }}:{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/date.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/datetime.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/input_option.html
{% if widget.wrap_label %}<label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}>{% endif %}{% include "django/forms/widgets/input.html" %}{% if widget.wrap_label %} {{ widget.label }}</label>{% endif %}

templates/django/forms/widgets/password.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/radio_option.html
{% include "django/forms/widgets/input_option.html" %}

templates/django/forms/widgets/select.html
<select name="{{ widget.name }}" class="form-select"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>

templates/django/forms/widgets/select_date.html
{% include 'django/forms/widgets/multiwidget.html' %}

templates/django/forms/widgets/select_option.html
<option value="{{ widget.value|stringformat:'s' }}"{% include "django/forms/widgets/attrs.html" %}>{{ widget.label }}</option>

templates/django/forms/widgets/splithiddendatetime.html
{% include 'django/forms/widgets/multiwidget.html' %}

templates/django/forms/widgets/text.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/url.html
{% include "django/forms/widgets/input.html" %}